# Generated by Django 6.0.2 on 2026-02-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('answer', 'Answer'), ('reply', 'Reply'), ('follow', 'Follow'), ('new_question', 'New Question')], max_length=20),
        ),
    ]
