# Generated by Django 6.0.2 on 2026-03-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='refresh_token',
            field=models.TextField(blank=True, default=''),
        ),
    ]
