# Generated by Django 6.0.2 on 2026-03-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_usersession_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='vote_type',
            field=models.CharField(choices=[('upvote', 'Upvote'), ('downvote', 'Downvote')], default='upvote', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'answer'), ('user', 'question'), ('user', 'reply')},
        ),
    ]
