# Generated by Django 6.0.2 on 2026-04-17 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_like_vote_type_alter_like_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
    ]
